# Generated by Django 5.2.3 on 2025-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_profile_image',
            new_name='profile_picture',
        ),
    ]
